name = "InhomogeneousBathymetryEuler"
uuid = "e15e5458-11a2-41b1-8d25-9cec07b2ece5"
authors = ["christoph-zetek"]
version = "1.0.0-DEV"

[deps]
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Ferrite = "1.0.0"
Interpolations = "0.15.1"
ProgressBars = "1.5.1"
SparseArrays = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
